language: java

env:
    - GRAALVM_VERSION="1.0.0-rc8"

install:
    - curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$GRAALVM_VERSION-linux-amd64.tar.gz" --output graalvm.tar.gz
    - tar -xvzf graalvm.tar.gz
    - export JAVA_HOME=$(pwd)/graalvm-ce-$GRAALVM_VERSION

script:
    - mvn package
    - ./sl language/tests/Add.sl
    - ./native/slnative language/tests/Add.sl
