os:
    - linux
    - osx

language: java

env:
    - GRAALVM_VERSION="1.0.0-rc8"

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$GRAALVM_VERSION-macos-amd64.tar.gz" --output graalvm.tar.gz; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$GRAALVM_VERSION-linux-amd64.tar.gz" --output graalvm.tar.gz; fi
    - tar -xzf graalvm.tar.gz
    - export JAVA_HOME="$(pwd)/graalvm-ce-$GRAALVM_VERSION"
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
    - echo $JAVA_HOME

script:
    - mvn package
    - ./sl language/tests/Add.sl
    - ./native/slnative language/tests/Add.sl
